### ISSUE TITLE
Whole installation process

### ISSUE THREAD

**Issue by pettod** [sanghyun-son/srwarp#1]
What is the complete installation process?

I ran into problem at running:
`conda env create --file environment.yaml`

```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement pysrwarp==1.0.0
ERROR: No matching distribution found for pysrwarp==1.0.0
```

My installation process was:
```
$ git clone https://github.com/sanghyun-son/srwarp
$ cd srwarp
$ git clone https://github.com/sanghyun-son/pysrwarp
$ cd pysrwarp
$ make
$ cd..
$ conda env create --file environment.yaml
```

**Comment by sanghyun-son** [comment]
Hi, pettod.

Maybe you can try after removing [line 85](https://github.com/sanghyun-son/srwarp/blob/6cee69ffb16d3c606547c401ba9e04605e79c9c9/environment.yaml#L85): - pysrwarp==1.0.0 in `environment.yaml`.

Please let me know if you have any further issues!

Thank you

**Comment by pettod** [comment]
Thank you sanghyun-son.

Here is my total process how it was setup successfully:

remove line 85 from environment.yaml
```
$ git clone https://github.com/sanghyun-son/srwarp
$ cd srwarp
$ git clone https://github.com/sanghyun-son/pysrwarp
$ cd pysrwarp
$ make
$ pip install -e .
$ cd..
$ conda env create --file environment.yaml
```

**Comment by ZYQii** [comment]
@pettod @sanghyun-son 
Hi pettod，  Hi sanghyun-son， I encountered a problem as follows：

Traceback (most recent call last):
  File "interactive.py", line 17, in <module>
    from srwarp import grid
ModuleNotFoundError: No module named 'srwarp'

How to solve it?  Thank you.
