### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [sanghyun-son/srwarp#4]
Thank you for sharing your great code. :smiley: 

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by sanghyun-son** [comment]
Hi, PINTO.

Thank you very much for your interest.

We have uploaded the LICENSE file.

Sanghyun
